services:
  analysis-env:
    image: karanb18/wine-quality-classification:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
