name: wine-quality
channels:
  - conda-forge
  - defaults
dependencies:
  - click
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - jupyter=1.1.1
  - python=3
  - numpy=1.26.4
  - altair=6.0.0
  - vl-convert-python
  - pandera=0.27.0
