name: wine-quality
channels:
  - conda-forge
  - defaults
dependencies:
  - click=8.3.1
  - pandas=2.2.2
  - scikit-learn=1.4.2
  - jupyter=1.1.1
  - python=3
  - numpy=1.26.4
  - altair=6.0.0
  - vl-convert-python=1.8.0
  - pandera=0.27.0
  - matplotlib=3.10.8
  - quarto=1.8.26
  - tabulate=0.9.0
  - pytest=9.0.2
